// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAST265iPsTVzkslf9VscTcyM5sfbJ1J88',
    appId: '1:716200804795:web:32819516e0de2a849f849e',
    messagingSenderId: '716200804795',
    projectId: 'mechcanic-app',
    authDomain: 'mechcanic-app.firebaseapp.com',
    storageBucket: 'mechcanic-app.appspot.com',
    measurementId: 'G-26RLQFSXGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwtaRPFUg4cgVnlcZkYjIZnf_CKbTxTQ',
    appId: '1:716200804795:android:4356cd760f10ce249f849e',
    messagingSenderId: '716200804795',
    projectId: 'mechcanic-app',
    storageBucket: 'mechcanic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8K_MsLNQoLz7d540_i_806fHRh8hbNI',
    appId: '1:716200804795:ios:5e5e2792f2d7178e9f849e',
    messagingSenderId: '716200804795',
    projectId: 'mechcanic-app',
    storageBucket: 'mechcanic-app.appspot.com',
    iosBundleId: 'com.example.mediConnect',
  );
}
